### PR TITLE
Dependency bot

### PR DESCRIPTION
**Pull request by ShiriNmi1520**
Add dependency bot for checking package update weekly

### CODE REVIEW

**Comment by thootau99** [comment]
weekly

**Comment by thootau99** [comment]
Kinda sus Amogus

**Comment by ShiriNmi1520** [comment]
Should we change it to weekly or something else? 🤔

**Review by thootau99 — APPROVED** [review]
seems sus

**Comment by thootau99** [comment]
too sus im gonna merge it

**Pull request merged**
